name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
        set -e
        npm run build
        cd docs/.vuepress/dist
        echo 'blog.project-heartfire.com' > CNAME
        git init
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:Seayay/hfp-blog-docs.git main:gh-pages
        cd -
